# Generated by Django 3.2.6 on 2021-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage_HarborData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('shipname', models.CharField(max_length=30)),
                ('worktype', models.CharField(max_length=20)),
            ],
        ),
    ]
