# Generated by Django 3.2.6 on 2021-08-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage_HarborData',
            new_name='HarborData',
        ),
    ]
